export const containerPaddingSize = 15;// 每个模块之间的内边距和外边距
export const columnPaddingSize = 20;// 上下边距
export const middleRadiusSize = 10;// 圆角大小
export const bigRadiusSize = 20;// 圆角大小
export const plusRadiusSize = 30;// 超大圆角
export const superRadiusSize = 50;// 加大版圆角
export const minBtnRadiusSize = 5;// 小圆角
export const middleBtnWidthSize = 70;// 中等按钮宽度
export const middleBtnHeightSize = 35;// 中等按钮高度
export const swiperHeightSize = 200; // 轮播高度
export const movieWidthSize = 150; // 电影图片宽度
export const movieHeightSize = 200;// 电影图片高度
export const modualHeightSize = 250;// 模块的高度
export const bigIconSize = 40;// 大图标
export const middleIconSize = 30;// 中等图标
export const smallIconSize = 20;// 中等图标
export const miniIconSize = 15;// 超小图片
export const smallMarginSize = 10;//小边距
export const miniMarginSize = 5;// 超小边距
export const smallFontSize = 14;//常规字体
export const middleFontSize = 16;//常规字体
export const bigFontSize = 20;// 大标题字体
export const middleAvaterSize = 40;// 中等头像
export const bigAvaterSize = 60;// 大头像
export const borderWidthSize = 1;// 边框大小
export const buttonHeightSize = 40;//按钮大小
export const crossAxisCountSize = 5;// 网格布局每行元素个数
export const childAspectRatioSize = 1.6;// 网格布局宽高比例
export const pageSize = 20;// 每页显示大小

